version: '3.9'

services:
  server:
    container_name: prakticum-server
    image: prackicum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    env_file:
      - .env
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - postgres
    environment:
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - default

  postgres:
    container_name: pg_container
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres
    networks:
      - default

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    networks:
      - default
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
    postgres:
    pgadmin:
