version: '3.9'

services:
  server:
    container_name: prakticum-server
    image: cr.yandex/crpunj11u18ujkuircm6/multiplayer-game:2bbce0b6f0f4733e7e9c3db9112f0d7e3d7ad2e7
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: 3001
    restart: always
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 3001
      VIRTUAL_HOST: odetocode-league-24.ya-praktikum.tech
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: odetocode-league-24.ya-praktikum.tech
    networks:
      - default

  postgres:
    container_name: pg_container
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - default

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=mail@odetocode-league-24.ya-praktikum.tech
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  postgres:
  volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  default:
    driver: bridge
