version: '3.9'

services:
  server:
    container_name: prakticum-server
    image: prackicum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    env_file:
      - .env
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - postgres
    environment:
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - default

  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    driver: bridge
